### ISSUE TITLE
Rate Limit Error.

### ISSUE THREAD

**Issue by Poojith-reddy** [pik1989/Resume-Parser-OpenAI#1]
![Screenshot 2024-08-16 160259](https://github.com/user-attachments/assets/f4e77b83-8430-4f34-bc10-517b0e5ceb75)

Any one kindly help me to resolve this issue, I didn't even tried this before, but It is showing the quota exceeded, What can I do now?

**Comment by pik1989** [comment]
The key that you are using has no credits, recharge it properly and retry the flow

**Comment by Poojith-reddy** [comment]
Ok, thank you for the quick response @pik1989
